### ISSUE TITLE
Add of dailyrainin value on log_all_sensorsWU.py

### ISSUE THREAD

**Issue by zoumpoulakis-manos** [raspberrypilearning/uploading-weather-data-to-weather-underground#32]
I use the Oracle Weather Station for schools and I send data to WU.
On this modified script, only the last hour's rainfall is send.
How can I add the `dailyrainin` value so I can have sum of the rainfall? [Info about dailyrainin here](http://wiki.wunderground.com/index.php/PWS_-_Upload_Protocol)

**Comment by zoumpoulakis-manos** [comment]
Sorry for posting again, anything news on this?

**Comment by topshed** [comment]
This isn't really an issue with the guide or the code - it is essentially a feature request.  I will add it to the list of possible future enhancements to the resource.
